### ISSUE TITLE
ADCIRCPY NOAA report

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoupledModelDriver#102]

**Comment by zacharyburnettNOAA** [comment]
duplicate of https://github.com/JaimeCalzadaNOAA/adcircpy/issues/50

**Comment by JaimeCalzadaNOAA** [comment]
PR: https://github.com/JaimeCalzadaNOAA/adcircpy/pull/57

**Comment by saeed-moghimi-noaa** [comment]
@JaimeCalzadaNOAA 
- wrap the comments and finalize
- cover pages
- Start communicating with Zizang 
- adobe test (accessibility)
