### ISSUE TITLE
share model run with Fei Ye

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/CoupledModelDriver#128]
share a model run directory with @feiye-vims 
- Florence 2018
- 120m HSOFS mesh
- `ATMESH` -> `ADCIRC` one-way coupling with NEMS

preferably a run directory with all output and log files

Fei's GLOBUS ID is `feiye`

**Comment by saeed-moghimi-noaa** [comment]
Yuji @ps2epsi  (perhaps the private account !?)

**Comment by zacharyburnettNOAA** [comment]
> Yuji @ps2epsi (perhaps the private account !?)

oh thank you

**Comment by zacharyburnettNOAA** [comment]
I apologize for not getting on this sooner; the model is now running on Hera and I will share it to `niagara` via Globus when it finishes.
```
(coupledmodeldriver)  Zachary.Burnett@hfe08 � /scratch2/COASTAL/coastal/scrub/Zachary.Burnett/working/zach/nems_adcirc/florence2018_hsofs120m_atmesh�
 > check_completion
{
    "florence2018_hsofs120m_atmesh": {
        "spinup": "running - 47.26%",
        "runs": "completed - 0%"
    }
}
```

**Comment by saeed-moghimi-noaa** [comment]
@zacharyburnettNOAA 

Thanks Zach, -Saeed

**Comment by feiye-vims** [comment]
Thank you, Zach! -Fei

**Comment by zacharyburnettNOAA** [comment]
I was able to complete the spinup, but the ATMESH -> ADCIRC hotstart run did not appear to run correctly. I will transfer the current state of the directory to niagara via Globus and keep working to get it up and running.
``` 
\(coupledmodeldriver)  Zachary.Burnett@hfe06 � /scratch2/COASTAL/coastal/scrub/Zachary.Burnett/workin/zach/nems_adcirc/florence2018_hsofs120m_atmesh/runs/unperturbed�                                                                                                                            
 > check_completion --v
{
    "unperturbed": {
        "status": "error",
        "progress": "0%",
        "error": {
            "ADCIRC_HOTSTART_unperturbed.err.log": [
                "application called MPI_Abort(comm=0x84000002, 1) - process 267\n",
                "application called MPI_Abort(comm=0x84000004, 1) - process 190\n"
...
```

**Comment by zacharyburnettNOAA** [comment]
It looks like I already have a Florence (2018) run with the old version of the HSOFS 120m mesh, here on Hera:
```
/scratch2/COASTAL/coastal/save/NAMED_STORMS/Florence_ADCIRC/run_20210812_florence_atmesh_120m_yujicopy_newnems
```
@feiye-vims I've copied it to Niagara-untrusted at this location, and will share it with your account:
```
/collab1/data_untrusted/Zachary.Burnett/runs/run_20210812_florence_atmesh_120m_yujicopy_newnems
```

**Comment by feiye-vims** [comment]
Thank you Zack!

I was able to download the files.

**Comment by zacharyburnettNOAA** [comment]
No problem! I apologize for the delay, I was unable to get the new mesh to run with my workflow. I will look more into this after the new year
