### ISSUE TITLE
HAMTIDE/TPXO

### ISSUE THREAD

**Issue by jreniel** [noaa-ocs-modeling/CoupledModelDriver#46]
https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/f52d9d8288b67435e1028730d53425b494fc2179/examples/hera/hera_hsofs_sandy.py#L37

For production you should use TPXO, as it includes tidal forcing constituents not present in HAMTIDE, which makes it (arguably) inherently more accurate.

**Comment by zacharyburnettNOAA** [comment]
fixed with 1a48dc93b1d580f751e0989b53a49ec346a4f68d
