### ISSUE TITLE
Job scripts and client py file

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoupledModelDriver#47]
Hi Zach

Here are issues that need to resolve:

1- the adcprep error is because of these new lines in the job_adcprep_hera.job:

DIRECTORY and ...

if you only keep **source** and **srun** lines you will be ok.

2- the f14 and 13 not linked to source and regenerated by adcircpy. This causes error.

-Saeed

**Comment by zacharyburnettNOAA** [comment]
> 1- the adcprep error is because of these new lines in the job_adcprep_hera.job:
fixed with 3b29329c132f676a7a3c586b9d19e6c663b087bd

> 2- the f14 and 13 not linked to source and regenerated by adcircpy. This causes error.
I'll work on this in #44
