### ISSUE TITLE
`ERROR: Elevation.gt.ErrorElev, ADCIRC stopping.` running HSOFS on Hera

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/CoupledModelDriver#51]
created a new branch `scratch/run_hsofs` with new parameters for `write_adcirc_configurations()`:

https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/db14b4482cf313cf4330e280093e59c655ffa6ce/examples/hera/hera_hsofs_sandy.py#L87-L89

**Comment by zacharyburnettNOAA** [comment]
```
(coupledmodeldriver)  Zachary.Burnett@hfe10  /scratch2/COASTAL/coastal/save/shared/working/zach/hera_hsofs_sandy_original_mesh_20210326/coldstart
 ➜ tail ADC_COLD_RUN.err.log -n 25
 TIME STEP =   21608     ITERATIONS =   17     TIME =  0.43216000E+05
  ELMAX =  8.0085E+002 AT NODE  1445920  SPEEDMAX =  3.0600E+001 AT NODE  1462099  ON MYPROC =  329   ** WARNING: Elevation.gt.WarnElev **
 TIME STEP =   21609     ITERATIONS =   17     TIME =  0.43218000E+05
  ELMAX =  9.9779E+002 AT NODE  1445921  SPEEDMAX =  3.1444E+001 AT NODE  1462099  ON MYPROC =  329   ** WARNING: Elevation.gt.WarnElev **
 TIME STEP =   21610     ITERATIONS =   17     TIME =  0.43220000E+05
  ELMAX =  1.3074E+003 AT NODE  1442537  SPEEDMAX =  4.1411E+001 AT NODE  1439160  ON MYPROC =  329   ** WARNING: Elevation.gt.WarnElev **
 TIME STEP =   21610     ITERATIONS =   17     TIME =  0.43220000E+05
  ELMAX =  1.3074E+003 AT NODE  1442537  SPEEDMAX =  4.1411E+001 AT NODE  1439160  ON MYPROC =  329
  ** ERROR: Elevation.gt.ErrorElev, ADCIRC stopping. **
srun: error: h25c25: tasks 440-479: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=17399392.0
srun: error: h23c11: tasks 120-159: Exited with exit code 1
srun: error: h23c29: tasks 240-279: Exited with exit code 1
srun: error: h25c30: tasks 480-519: Exited with exit code 1
srun: error: h25c39: tasks 560-599: Exited with exit code 1
srun: error: h23c28: tasks 200-239: Exited with exit code 1
srun: error: h25c24: tasks 400-439: Exited with exit code 1
srun: error: h25c06: tasks 280-319: Exited with exit code 1
srun: error: h25c22: tasks 360-399: Exited with exit code 1
srun: error: h25c21: tasks 320-359: Exited with exit code 1
srun: error: h1c50: tasks 40-79: Exited with exit code 1
srun: error: h1c48: tasks 0-39: Exited with exit code 1
srun: error: h23c10: tasks 80-119: Exited with exit code 1
srun: error: h25c37: tasks 520-559: Exited with exit code 1
srun: error: h23c12: tasks 160-199: Exited with exit code 1
```

**Comment by saeed-moghimi-noaa** [comment]
@JaimeCalzadaNOAA  @zacharyburnettNOAA 

We need to make sure we  reproduce fort.15 similar to:
**HSOFS_nosubset_al062018_ColdStart.15**
Storm Code: al062018
HSOFS_nosubset_al062018-CS
1         	 ! NFOVER 
0        	 ! NABOUT 
18719        	 ! NSCREEN 
0        	 ! IHOT 
22        	 ! ICS 
511112        	 ! IM 
1        	 ! NOLIBF 
2        	 ! NOLIFA 
1        	 ! NOLICA 
1        	 ! NOLICAT 
5        	 ! NWP 
mannings_n_at_sea_floor
primitive_weighting_in_continuity_equation
surface_canopy_coefficient
surface_directional_effective_roughness_length
surface_submergence_state
1   	 	 ! NCOR 
1   	 	 ! NTIP 
0   	 	 ! NWS 
1   	 	 ! NRAMP 
9.810000   	 ! G  
-3   	 	 ! TAU0 
4.6154  	 	 ! DTDP 
0  	 	 ! STATIM 
0  	 	 ! REFTIM 
10   	 	 ! RNDY 
5  	 	 ! DRAMP 
0 1 0  	 ! A00, B00, C00 
0.1 0 0 0.01    	 ! H0, 2*dummy, VELMIN 
-82.127229 31.327672  	 	 ! SLAM0, SFEA0 
0.002500     	 ! CF 
-0.200000     	 ! ELSM 
0.000000   	 ! CORI 


**HSOFS_nosubset_al062018_HotStart.15**
Storm Code: al062018
HSOFS_nosubset_al062018-HS
1         	 ! NFOVER 
0        	 ! NABOUT 
18719        	 ! NSCREEN 
567        	 ! IHOT 
22        	 ! ICS 
511112        	 ! IM 
1        	 ! NOLIBF 
2        	 ! NOLIFA 
1        	 ! NOLICA 
1        	 ! NOLICAT 
5        	 ! NWP 
mannings_n_at_sea_floor
primitive_weighting_in_continuity_equation
surface_canopy_coefficient
surface_directional_effective_roughness_length
surface_submergence_state
1   	 	 ! NCOR 
1   	 	 ! NTIP 
20   	 	 ! NWS 
8   	 	 ! NRAMP 
9.810000   	 ! G  
-3   	 	 ! TAU0 
4.6154  	 	 ! DTDP 
0  	 	 ! STATIM 
0  	 	 ! REFTIM 
2018 9 1 6 1 0.9 1  	 ! YYYY MM DD HH24 StormNumber BLAdj geofactor 
16.5   	 	 ! RNDY 
0 0 0 0 0 0 0.5 0 10  	 	 ! DRAMP 
0 1 0  	 ! A00, B00, C00 
0.1 0 0 0.01    	 ! H0, 2*dummy, VELMIN 
-82.127229 31.327672  	 	 ! SLAM0, SFEA0 
0.002500     	 ! CF 
-0.200000     	 ! ELSM 
0.000000   	 ! CORI 
8   	 	 ! NTIF
