### ISSUE TITLE
add more `adcircpy` driver options to `ADCIRCJSON` object

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/CoupledModelDriver#74]
The `ADCIRCJSON` object can read and write the `configure_adcirc.json` file, and inputs the options to pass to the mesh and driver. Currently, only the following options are implemented and propagated to the driver:
- `modeled_timestep`
- `gwce_solution_scheme`
- `use_smagorinsky`
- `tidal_spinup_duration`
- `write_station_output`
- `write_surface_output`

https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/b8d7f4c44eccb6c2ee5d2268d082c1ed30ffb4e1/coupledmodeldriver/configure/models.py#L244-L281

**Comment by zacharyburnettNOAA** [comment]
## Current JSON entries
https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/b8d7f4c44eccb6c2ee5d2268d082c1ed30ffb4e1/coupledmodeldriver/configure/models.py#L123-L138

## Current code for creating Mesh object
https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/b8d7f4c44eccb6c2ee5d2268d082c1ed30ffb4e1/coupledmodeldriver/configure/models.py#L194-L229

## Current code for creating Driver object
https://github.com/noaa-ocs-modeling/CoupledModelDriver/blob/b8d7f4c44eccb6c2ee5d2268d082c1ed30ffb4e1/coupledmodeldriver/configure/models.py#L231-L283

**Comment by zacharyburnettNOAA** [comment]
@JaimeCalzadaNOAA this is more of a backburner project, but are there a few uber-important options that definitely should be included in a JSON config, or should I just work to include all of the possible options that can be passed to `AdcircRun`?

Also, I assume there are some options that should NOT be included in the JSON, such as directly setting `IM`

**Comment by zacharyburnettNOAA** [comment]
after talking with @saeed-moghimi-noaa , we discussed adding output frequency (`TOUTSGE,` , `TOUTFGE`, etc.)

**Comment by zacharyburnettNOAA** [comment]
I've implemented the following attributes of the `AdcircRun` object:
```
predictor_corrector
RUNDES
_IHOT
RUNID
NFOVER
WarnElev
iWarnElevDump
WarnElevDumpLimit
ErrorElev
NABOUT
NSCREEN
IDEN
NOLIBF
NOLICA
NOLICAT
NCOR
NTIP
G
TAU0
DTDP
STATIM
REFTIM
DRAMP
DRAMPExtFlux
FluxSettlingTime
DRAMPIntFlux
DRAMPElev
DRAMPTip
DRAMPMete
DRAMPWRad
DUnRampMete
H0
NODEDRYMIN
NODEWETRMP
VELMIN
SLAM0
SFEA0
FFACTOR
CF
HBREAK
FTHETA
FGAMMA
ESLM
NOUTGE
TOUTSGE
TOUTFGE
NSPOOLGE
NOUTGV
TOUTSGV
TOUTFGV
NSPOOLGV
NOUTGM
TOUTSGM
TOUTFGM
NSPOOLGM
NOUTGC
TOUTSGC
TOUTFGC
NSPOOLGC
CORI
ANGINN
THAS
THAF
NHAINC
FMV
NHSTAR
NHSINC
ITITER
ISLDIA
CONVCR
ITMAX
NCPROJ
NCINST
NCSOUR
NCHIST
NCREF
NCCOM
NCHOST
NCCONV
NCCOUT
vertical_mode
lateral_stress_in_gwce
lateral_stress_in_gwce_is_symmetrical
adcvection_in_gwce
lateral_stress_in_momentum
lateral_stress_in_momentum_is_symmetrical
lateral_stress_in_momentum_method
adcvection_in_momentum
area_integration_in_momentum
baroclinicity
gwce_solution_scheme
passive_scalar_transport
stress_based_3D
smagorinsky
smagorinsky_coefficient
horizontal_mixing_coefficient
CFL
```

**Comment by saeed-moghimi-noaa** [comment]
Zach, Are these also being recorded in json file?


On Thursday, April 22, 2021, Zachary Burnett ***@***.***>
wrote:
> I've implemented the following attributes of the AdcircRun object:
>
> predictor_corrector
> RUNDES
> _IHOT
> RUNID
> NFOVER
> WarnElev
> iWarnElevDump
> WarnElevDumpLimit
> ErrorElev
> NABOUT
> NSCREEN
> IDEN
> NOLIBF
> NOLICA
> NOLICAT
> NCOR
> NTIP
> G
> TAU0
> DTDP
> STATIM
> REFTIM
> DRAMP
> DRAMPExtFlux
> FluxSettlingTime
> DRAMPIntFlux
> DRAMPElev
> DRAMPTip
> DRAMPMete
> DRAMPWRad
> DUnRampMete
> H0
> NODEDRYMIN
> NODEWETRMP
> VELMIN
> SLAM0
> SFEA0
> FFACTOR
> CF
> HBREAK
> FTHETA
> FGAMMA
> ESLM
> NOUTGE
> TOUTSGE
> TOUTFGE
> NSPOOLGE
> NOUTGV
> TOUTSGV
> TOUTFGV
> NSPOOLGV
> NOUTGM
> TOUTSGM
> TOUTFGM
> NSPOOLGM
> NOUTGC
> TOUTSGC
> TOUTFGC
> NSPOOLGC
> CORI
> ANGINN
> THAS
> THAF
> NHAINC
> FMV
> NHSTAR
> NHSINC
> ITITER
> ISLDIA
> CONVCR
> ITMAX
> NCPROJ
> NCINST
> NCSOUR
> NCHIST
> NCREF
> NCCOM
> NCHOST
> NCCONV
> NCCOUT
> vertical_mode
> lateral_stress_in_gwce
> lateral_stress_in_gwce_is_symmetrical
> adcvection_in_gwce
> lateral_stress_in_momentum
> lateral_stress_in_momentum_is_symmetrical
> lateral_stress_in_momentum_method
> adcvection_in_momentum
> area_integration_in_momentum
> baroclinicity
> gwce_solution_scheme
> passive_scalar_transport
> stress_based_3D
> smagorinsky
> smagorinsky_coefficient
> horizontal_mixing_coefficient
> CFL
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/fS51hHTc6mrcVnfpKuDLeQb_DkuIM_HCrc9S8DHpPTHX38zHEVd9a8Fh0DIL9D24E5iNNw3QV_xwF7ARFRedR8UeKoSWeIXeWRtl212hTExmK0nYYRMwBG8afovaZ8Vz6ZZ47ni4w9msNh8fbSzXaa5-UuEB6Ty3r3pHti9LRcdZk0QOGPG9Y1TYW_PMoFkfSDQiiqwWRwds_8EzoZTKMF1FgDnslQA4LF1t8J3rWA=s0-d-e1-ft#https://github.com/notifications/beacon/APZULDZMYKD3DN4SBSJU46LTKBYKLA5CNFSM423G7PSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGEXEI3Q.gif
>

-- 
______________________________________________________
Saeed Moghimi, PhD
*UCAR/NOAA - NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910
Phone: (240) 847-8230

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by zacharyburnettNOAA** [comment]
@saeed-moghimi-noaa yes they are recorded in the `attributes` entry as a dictionary. I also added a (smaller) `attributes` entry to the BestTrack JSON containing the following:
```
NWS
BLADj
_storm_id
geofactor
start_date
end_date
```

**Comment by saeed-moghimi-noaa** [comment]
Thanks.

On Thursday, April 22, 2021, Zachary Burnett ***@***.***>
wrote:
> @saeed-moghimi-noaa yes they are recorded in the attributes entry as a
dictionary. I also added a (smaller) attributes entry to the BestTrack JSON
containing the following:
>
> NWS
> BLADj
> _storm_id
> geofactor
> start_date
> end_date
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/M0E52JBqrnZXP4WtgItRgqX_9KfQYAfNPgH5aIqrsYIYvQFcMA4dmfSV8som1otAd1ssChNQM2POuXk8lqkXdcjYgSh-F6Zo1_UwXyaHVBjdDyOFqYw6ohzeOHKEqwGXlOPacl9VGlxhfFfoLEECJG_hV99tACCB3pfzwTNFw5zb49KrxogQDqb02eH3w-7gvghpBXbfvu_n5XduGHOmiDJFrkgzZFh0eYLo56pMhQ=s0-d-e1-ft#https://github.com/notifications/beacon/APZULD6KKZKTRITXGUMLCI3TKB2FDA5CNFSM423G7PSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGEXGYAI.gif
>

-- 
______________________________________________________
Saeed Moghimi, PhD
*UCAR/NOAA - NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910
Phone: (240) 847-8230

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.
