### ISSUE TITLE
build several perturbed runs by passing multiple `fort.22` filenames

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/CoupledModelDriver#84]
in the `runs` dictionary in `configure_modeldriver.json`

@WPringle do you have some perturbed `fort.22` files that I could use to test with?

**Comment by WPringle** [comment]
Still working on that this afternoon. I'll share this repo I'm working on with you. See the Storm-Surge-Mesh-Subsetting/ATCF/make_storm_ensemble.py file within that which trying to use to generate the ensembles.

**Comment by WPringle** [comment]
@zacharyburnettNOAA the make_storm_ensemble.py can now produce ensembles for Vmax. Need one more update to also change central in congruence with Vmax. 

example call for Hurricane Florence:
python3 make_storm_ensemble.py al062018 2018090106 2018091718

**Comment by WPringle** [comment]
Cleaned up the script and now perturbs central pressure along with Vmax at the same time.

**Comment by zacharyburnettNOAA** [comment]
> 
> 
> Cleaned up the script and now perturbs central pressure along with Vmax at the same time.

I'm getting an error when trying to set the `._df` attribute, I'll look into the code https://github.com/WPringle/Storm-Surge-Mesh-Subsetting/issues/2

**Comment by WPringle** [comment]
Yep I've been using that PR adcircpy with the setter. Eventually, I think will be better to improve the best_track module itself and add some of the options from the make_storm_ensemble into it.

**Comment by zacharyburnettNOAA** [comment]
I've generated a set of hotstart configurations in the following directory:
```
/scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds
```
this is still using the unsubsetted mesh; my next item on the todo is to make a run incorporating the subsetted mesh

**Comment by zacharyburnettNOAA** [comment]
currently running jobs:
```
   JOBID CPU NODE WORK_DIR                                                                                                         NAME
18228203 640 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0/runs/unperturbed     ADC_HOT_RUN
18228846 600 15   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/c ADC_COLD_RUN
18228847 1   1    /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_MESH_DECOMP
18228848 601 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_HOT_RUN
18228849 1   1    /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_MESH_DECOMP
18228850 601 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_HOT_RUN
18228851 1   1    /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_MESH_DECOMP
18228852 601 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210422_hsofs_250m_v1.0_besttrack_maxwinds/r ADC_HOT_RUN
```

**Comment by zacharyburnettNOAA** [comment]
3 perturbations 
```
maxwinds_1.22  maxwinds_10.22  maxwinds_11.22
```
currently running at 
```
/scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210429_hsofs_120m_subsetflo_besttrack_maxwinds
```

currently running jobs:
```
   JOBID CPU NODE WORK_DIR                                                                                          NAME
18426178 640 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210429_hsofs_120m_subsetflo_ ADCIRC_HOTSTART
18426180 640 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210429_hsofs_120m_subsetflo_ ADCIRC_HOTSTART
18426182 640 16   /scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210429_hsofs_120m_subsetflo_ ADCIRC_HOTSTART
```

**Comment by zacharyburnettNOAA** [comment]
related to #86

**Comment by zacharyburnettNOAA** [comment]
it looks like the `fort.22` input is working well, so I will close this issue and fold the best track effort into #87
