### ISSUE TITLE
generate perturbed best tracks

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/CoupledModelDriver#87]
perturb the following:

- [x] `Rmax`
- [x] `Vmax`
- [x] spatial track perturbation (w/ `shapely`) #87

**Comment by zacharyburnettNOAA** [comment]
related issues:
- https://github.com/JaimeCalzadaNOAA/adcircpy/pull/60
- https://github.com/noaa-ocs-modeling/CoupledModelDriver/issues/84

**Comment by zacharyburnettNOAA** [comment]
related to #84

**Comment by zacharyburnettNOAA** [comment]
spatial track perturbation is enclosed in #88

**Comment by zacharyburnettNOAA** [comment]
now building bridge between EnsemblePerturbation -> CoupledModelDriver to build perturbed run

**Comment by saeed-moghimi-noaa** [comment]
Hi Zach, @zacharyburnettNOAA  @wpringle

Any update on the full ensemble run for all variables for:
- [ ] ADCIRC alone
- [ ] NEMS app

Thanks,
-Saeed

**Comment by WPringle** [comment]
Hi @saeed-moghimi-noaa Zach did some ensemble test runs using updated adcirc inputs that I suggested. Could you please copy over to the share folder on Orion so I can check them out?

**Comment by saeed-moghimi-noaa** [comment]
@zacharyburnettNOAA  @WPringle 

Hi
I need to know where the flies are located. Zach please use Globus to move the data. Let me know if you need help.

Thanks,
-Saeed

**Comment by WPringle** [comment]
@zacharyburnettNOAA Actually I am able to access your folder` /work/noaa/nosofs/share/models` so if you could make a folder for Florence test case with same permissions as that on share I will be able to access

**Comment by zacharyburnettNOAA** [comment]
hey, sorry I did not see these comments. I've finished the bridge between `ensembleperturbation` -> `coupledmodeldriver` and am currently running 2 runs of 12 perturbations each on Hera:
```
/scratch2/COASTAL/coastal/save/shared/working/zach/adcirc/run_20210616_hsofs_120m_subsetflo_perturbedtracks
/scratch2/COASTAL/coastal/save/shared/working/zach/nems_adcirc/run_20210616_hsofs_120m_subsetflo_perturbedtracks
```

@WPringle I've put the model runs in `/work/noaa/nosofs/share/working/zach/adcirc`, and am using `/work/noaa/nosofs/share/models` to store input data like forcings and meshes. I've set `chmod ugo+rw` for all of the folders in `share` so let me know if you aren't able to access them

**Comment by WPringle** [comment]
Thanks @zacharyburnettNOAA . But, I'm not able to access the working directory, although I can access the models one. Can you please change the working one and its subfolders.

**Comment by saeed-moghimi-noaa** [comment]
@zacharyburnettNOAA  Please

**Comment by zacharyburnettNOAA** [comment]
> Thanks @zacharyburnettNOAA . But, I'm not able to access the `working/` directory, although I can access the `models/` one. Can you please change the working one and its subfolders.

I think I found the problem; I gave `chmod ugo+rw working -R` but did not give executable, and I think in order to `cd` into a directory you need `X`. I just added that to the directory, see if it works now

**Comment by zacharyburnettNOAA** [comment]
To do:
- [ ] fix track perturbation (all track files are identical)
- [ ] add `ICS` parameter to `adcircpy` and `coupledmodeldriver`
