### ISSUE TITLE
share shapely scripts with william

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoupledModelDriver#89]
share shapely scripts with william

**Comment by saeed-moghimi-noaa** [comment]
@wpringle @zacharyburnettNOAA 

See this file functions and the main code at the end How I use linestring functions ...

Happy to walk you through next time

https://github.com/moghimis/pybathy/blob/main/s02_saint_john_spline_v03_good.py

**Comment by zacharyburnettNOAA** [comment]
I was doing something similar with alpha shapes in the NBS project, maybe I can borrow some of that code as well.

Either way, `shapely` seems to be the way to go with this track perturbation effort.
